[package]
name = "alveus-kart"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = "0.4.0"
bevy = { "version" = "0.17.2", features = ["jpeg"] }
bevy-tnua = "0.26.0"
bevy-tnua-avian3d = "0.8.0"
bevy_third_person_camera_2 = "0.1.8"
glam = "0.30.9"
